#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/coupon
#    username: root
#    password: 1234


#spring:
#  profiles:
#    default: local
#
#  datasource:
#    url: jdbc:h2:mem:~/cafeKioskApplication
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#---
#spring:
#  config:
#    activate:
#      on-profile: local
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행
#
#  h2:
#    console:
#      enabled: true
#---
#spring:
#  config:
#    activate:
#      on-profile: test
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  sql:
#    init:
#      mode: never

spring:
  datasource:
    url: jdbc:h2:mem:testdb   # 메모리 모드 H2 DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create        # 애플리케이션 실행 시 테이블 생성
    show-sql: true            # 실행되는 SQL 출력
    properties:
      hibernate:
        format_sql: true      # SQL 포맷팅해서 출력
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행
  h2:
    console:
      enabled: true           # H2 웹 콘솔 활성화
      path: /h2-console       # 콘솔 접속 경로
